package net.ccbluex.liquidbounce.utils

object StaffList {
    const val CUBECRAFT: String = "S4nne " +
            "Fesa " +
            "99th_DutchScary " +
            "Soulless_Unity " +
            "EggyWarz " +
            "Efcluke94 " +
            "SanCookie " +
            "CKelting262 " +
            "rubik_cube_man " +
            "ToonBer " +
            "Kloska " +
            "xThunder_ " +
            "CapitanGato " +
            "SuperSuccubus " +
            "Otherworlden " +
            "ssunsett " +
            "Hqteful " +
            "Alexp192 " +
            "4Moonlightt " +
            "ALM " +
            "xSchulzis " +
            "Muhx " +
            "Goofy_Unity " +
            "ThijsBlocker " +
            "Redned " +
            "Lyriie " +
            "JustNathie " +
            "JokeKaedee " +
            "Elivat " +
            "MDeann " +
            "Basketman13 " +
            "AnolTongi " +
            "Alemiz " +
            "Camezonda "

    const val KKCRAFT: String = "Creeper_Hello Kun_God hanhan_api Regotly_Long"
    const val HYPIXEL: String = "Hypixel " +
            "Rezzus " +
            "AgentK " +
            "Cryptkeeper " +
            "Minikloon " +
            "Plancke " +
            "Slothpixel " +
            "NoxyD " +
            "Jayavarmen " +
            "aPunch " +
            "Gerbor12 " +
            "JordWG " +
            "LeBrillant " +
            "Pensul " +
            "LadyBleu " +
            "Citria " +
            "DeluxeRose " +
            "TheBirmanator " +
            "TorWolf " +
            "Rhune " +
            "Greeenn " +
            "Fr0z3n " +
            "SnowyPai " +
            "Rozsa " +
            "Quack " +
            "ZeaBot " +
            "Cheesey " +
            "MCVisuals " +
            "carstairs95 " +
            "DistrictGecko " +
            "inventivetalent " +
            "JacobRuby " +
            "Judg3 " +
            "LandonHP " +
            "Liffeh " +
            "xHascox " +
            "DEADORKAI " +
            "Brandonjja " +
            "skyerzz " +
            "Dctr " +
            "AdamWho " +
            "jamzs " +
            "Phaige " +
            "Likaos " +
            "Plummel " +
            "Bloozing " +
            "BlocksKey " +
            "MistressEldrid " +
            "Nausicaah " +
            "ChiLynn " +
            "TheMGRF " +
            "Revengeee " +
            "_PolynaLove_ " +
            "Sylent_ " +
            "Teddy " +
            "Relenter " +
            "_fudgiethewhale " +
            "sfarnham " +
            "WilliamTiger " +
            "vinny8ball666 " +
            "Nitroholic_ " +
            "Donpireso " +
            "ConnorLinfoot " +
            "RapidTheNerd " +
            "eeyitscoco " +
            "Cecer " +
            "Externalizable " +
            "Bembo " +
            "Taytale " +
            "JamieTheGeek " +
            "williamgburns " +
            "BOGA32 " +
            "boomerzap " +
            "MFN " +
            "Gainful " +
            "Octaverei " +
            "TacNayn " +
            "TimeDeo " +
            "idhoom " +
            "7so " +
            "1sweet " +
            "jinaaan " +
            "ev2n " +
            "eissaa " +
            "mohmad_q8 " +
            "1daykel " +
            "ximtaig_ " +
            "nshme " +
            "comsterr " +
            "e9_ " +
            "1meko " +
            "1lab " +
            "mk_f16 " +
            "loovq " +
            "_sadeq " +
            "nv0ola " +
            "1f5amh___3oo " +
            "frecss217 " +
            "xmz7 " +
            "a2bod " +
            "eyeso_diamond " +
            "bunkrat " +
            "1rana " +
            "1ahmd " +
            "1heyimhasson_ " +
            "casteret " +
            "1elyy " +
            "1zeyad " +
            "lt1x " +
            "firas " +
            "postme " +
            "3mmr " +
            "xl2d " +
            "yzed " +
            "y2men " +
            "iv2a " +
            "_nonameishere_ " +
            "0hfault " +
            "deficency " +
            "anauri " +
            "xluffy1 " +
            "kinderbueno__ " +
            "_revoox_ " +
            "xidayzer " +
            "i7ilin " +
            "1adam__ " +
            "27bk " +
            "ventz_ " +
            "awfultimes " +
            "ahm2d " +
            "gsomar " +
            "mvp11 " +
            "xxkhaledxxcraft " +
            "aymann_ " +
            "1iraqi " +
            "rambokinq " +
            "undertest " +
            "zswift " +
            "strongest0ne " +
            "neverletyouknow " +
            "zixgamer " +
            "sanfoor_j " +
            "ixghoul_ " +
            "imbexsl_ " +
            "glowdown_ " +
            "hunter47 " +
            "fexoranep " +
            "1reyleigh " +
            "420waffle " +
            "ywgiz " +
            "sweetyalice " +
            "xfahadq " +
            "mr3nb_ " +
            "akash1004 " +
            "zaytonaaa " +
            "rma7o " +
            "mr_1990 " +
            "iali_305 " +
            "wacros " +
            "lwwh " +
            "pynifical " +
            "rivsci " +
            "itsjuan_ " +
            "meedo_qb " +
            "_r3 " +
            "1speedo_ " +
            "_justidk " +
            "505t " +
            "xzvv " +
            "mauveracer " +
            "_1hypersx_ " +
            "rayqquaza " +
            "swivee " +
            "absqtulate " +
            "opgaming2009 " +
            "vhagardracarys " +
            "luffy404 " +
            "faisaal420 " +
            "hdzt " +
            "sunsnipebeastwtf " +
            "_odex " +
            "1ashu " +
            "n13m_ " +
            "callinu " +
            "sh59 " +
            "drnyx " +
            "iisrab5bgii " +
            "haoeris " +
            "lxrayanxl " +
            "toxiclayer " +
            "greatm7md " +
            "brksfrb2 " +
            "madix707 " +
            "hnxrr " +
            "1sweetty " +
            "ohhhhqls " +
            "solidfying " +
            "_i_b " +
            "escoco " +
            "dreadpirater0b " +
            "aboshxm " +
            "0ryze " +
            "spuvr " +
            "va_1 " +
            "kingpvp90 " +
            "rieus " +
            "prebowed " +
            "mitsichu " +
            "gogglas " +
            "battlebay " +
            "32lbo " +
            "7far_8bor " +
            "evenfai " +
            "hlazny " +
            "valrm "

    const val PIKA: String = "Max " +
            "voodootje0 " +
            "MrFrenco " +
            "JustThiemo " +
            "Wrath " +
            "Andeh " +
            "Nirahz " +
            "stupxd " +
            "Botervrij " +
            "Subvalent " +
            "Apo2xd " +
            "Arrly " +
            "Minecraft_leg " +
            "CaptainGeoGR " +
            "Thijme01 " +
            "ChickenDinnr " +
            "Crni_ " +
            "MrGownz " +
            "Outscale " +
            "MrEpiko " +
            "Crveni_Marlboro " +
            "zMqrcc " +
            "_Stella_xD " +
            "Stormidity " +
            "TryToHitMe " +
            "Alparo_ " +
            "CandyOP " +
            "Astrospeh " +
            "TinCanL " +
            "TheTrueNova " +
            "FIKOZ " +
            "DarkVenom7 " +
            "caila5 " +
            "Lpkfvip " +
            "i9BAR " +
            "voodootjeo " +
            "TryHardMarktin " +
            "Axteroid " +
            "Yanique1 " +
            "JstMental " +
            "QuFox " +
            "TTHM " +
            "shozu " +
            "Aeqlian " +
            "NxqL " +
            "iFkiller " +
            "xDeleted " +
            "_Nikki99 " +
            "SgtBordem " +
            "Sanified " +
            "M7Games_HD " +
            "DanielT_ " +
            "Zxga " +
            "Ungluecklicher " +
            "zireb " +
            "GAMBL3T " +
            "RunYourShordie " +
            "ScorchedX " +
            "zSeann " +
            "YouTubeMemes " +
            "CreeperDxD " +
            "Saifanx1942 " +
            "arham19 " +
            "prober90 "

    const val BMC: String = "vFahad_ " +
            "mufazzz " +
            "arbde " +
            "Webmasters " +
            "Vampirec " +
            "zAtTiLq " +
            "DirectPlan " +
            "PeerfectRod_ " +
            "1F5aMH___3oo " +
            "Aliiyah " +
            "deficency " +
            "EyesO_Diamond " +
            "F2rris " +
            "1flyn " +
            "Nadaa " +
            "Morninng " +
            "KinderBueno__ " +
            "bestleso " +
            "Reflxctively " +
            "ImMEHDI_ " +
            "Ixfaris_0 " +
            "Aymann_ " +
            "xfahadq " +
            "BoMshary " +
            "1Adam__ " +
            "ALMARDAWI " +
            "Postme " +
            "xL2d " +
            "DrugsOverdose " +
            "Om2r " +
            "0ayt " +
            "5ald_KSA " +
            "GsMrxDJ " +
            "GsOMAR " +
            "TryLat3rjAs " +
            "Ruwq " +
            "teddynicelol " +
            "MightyM7MD " +
            "itsjust24 " +
            "Jrx7 " +
            "Mwl4 " +
            "m7mdxjw " +
            "Jxicide " +
            "Vengeant " +
            "kieax " +
            "Mr_1990 " +
            "JustRois_ " +
            "CASHFL0WW " +
            "A3loosh " +
            "Neeres " +
            "luqqr " +
            "_1Dark " +
            "Werthly " +
            "1Khalid " +
            "LovelyMaram " +
            "dxs7 " +
            "1Az_ " +
            "0Strong " +
            "Y2sF " +
            "Morgan_So " +
            "z1HypersXz " +
            "MILG511 " +
            "tHeViZi " +
            "_Lsantoss " +
            "MVP11 " +
            "MightyFiras " +
            "xVerif " +
            "1Sharlock " +
            "whahahahahahaha " +
            "wallacce " +
            "BPEJ " +
            "GymIsTherapy " +
            "0Leqf " +
            "Ditraghxel " +
            "Claegness " +
            "catbisou " +
            "Attraactive " +
            "M5CS_ " +
            "Xx_ZeroMc_xX " +
            "_IxM " +
            "yyodey " +
            "K2reem " +
            "Dfivz " +
            "KingH0 " +
            "Time98 " +
            "rosulate " +
            "glowingsunsets " +
            "Yarin " +
            "OnlyK1nq " +
            "YOUVA " +
            "I_Shling " +
            "0PvP_ " +
            "FANOR_SYR " +
            "NamikazeMin4to " +
            "Bradenton " +
            "Watchdog " +
            "2lbk " +
            "m7xar " +
            "1LoST_ " +
            "Rikoshy " +
            "GsYousef " +
            "iidouble " +
            "5bzzz " +
            "Just_XYZ " +
            "TruthZ_ " +
            "Ovqrn " +
            "9lrv " +
            "_iMuslim_ " +
            "5loo " +
            "PavleDjajic " +
            "D7iiem " +
            "SweetyAlice " +
            "7amze__ " +
            "D_1V " +
            "Abo_3losh " +
            "Lyrnxx " +
            "1Pre " +
            "Peree " +
            "Everlqst " +
            "Gaboo6 " +
            "FastRank " +
            "Erosiion " +
            "EgaSS " +
            "Vanitas_0 " +
            "PoisonL " +
            "1Prometheus_ " +
            "Pogor " +
            "ixstorm_ " +
            "1MSA " +
            "AnotherHero " +
            "D3vi1Joex " +
            "38l_ba6n " +
            "izLORDeX " +
            "RAGHAVV " +
            "Impassivelly " +
            "Reixo " +
            "NotriousAsser " +
            "DasPukas_ " +
            "1Abd2llah " +
            "swhq " +
            "1ith " +
            "ArabPixel " +
            "Majd83 " +
            "Mxhesh " +
            "LIONMohamed " +
            "4T0_ " +
            "Mc_Suchter " +
            "Mo3Az1 " +
            "B7rl " +
            "TheCre4tor " +
            "ln5b " +
            "BasilFoto " +
            "einmeterhecht " +
            "BeFriends " +
            "1Sweet " +
            "Ev2n " +
            "xMz7 " +
            "xiDayzer " +
            "mohmad_q8 " +
            "Ceulla " +
            "Nshme " +
            "Firas " +
            "e9_ " +
            "1LaB " +
            "Bunkrat " +
            "0HqSon_ " +
            "0bowskills " +
            "Iv2a " +
            "_sadeq " +
            "1Meran " +
            "A2boD "

    const val ARERAPVP: String = "Agera001 " +
            "Krashe85 " +
            "milanskyy " +
            "Neruxov " +
            "softrelax " +
            "quiu " +
            "exac123 " +
            "Ant4b " +
            "tenfey " +
            "bumyyy1 " +
            "s11an " +
            "spookyjonn " +
            "smothes " +
            "MilkyDream " +
            "22aroma " +
            "Ska1ras " +
            "Twitch_Weathers " +
            "cyceki " +
            "oldlegend " +
            "HEMECUYA " +
            "Uister " +
            "kairomuza " +
            "Rustas23 " +
            "Akiroxy " +
            "montegs " +
            "Duffy_Who " +
            "tiroeson " +
            "ne_dasty"

    const val HYPEMC: String = "chromocat " +
            "KaVlVi " +
            "Twintle " +
            "teisenshi " +
            "_MerticksX_ " +
            "CcPhoenixcC " +
            "rope " +
            "milian " +
            "miamha " +
            "docya " +
            "tudaiobrattno " +
            "x4bb " +
            "loqxnew " +
            "RydiEndi " +
            "Lia2806 " +
            "Gamrely " +
            "Heron " +
            "Ryafkaa " +
            "SoMDeaS " +
            "_GromoV_ " +
            "ygolokk " +
            "Pomachka58 " +
            "LISSKX " +
            "v1nd1go " +
            "Ksenchiks " +
            "FixVaR " +
            "Max540 " +
            "Biikysi " +
            "De_La_Vult " +
            "Akiro49 " +
            "Antos4597 " +
            "Looon " +
            "Bratskyy " +
            "Sursus_S " +
            "ItzAKreyz " +
            "fondik33 " +
            "_tepan098kop_ " +
            "xXx_ST0RM_xXx " +
            "Munchen " +
            "_Or1on_ " +
            "DimonGonBon " +
            "_Dead_Lord_ " +
            "Maksun65yg47tq " +
            "Chizzylegend " +
            "MEDYK " +
            "312 " +
            "Grr441235 " +
            "pinm_qw " +
            "rubick_dash " +
            "IsterBEAk " +
            "Pro100pavel2006 " +
            "Yaguzhinskiy " +
            "Hi11Ti " +
            "glebgeniy " +
            "swiGEMAAOO " +
            "Mr_GeoMheo " +
            "филин223 " +
            "king335xxx " +
            "sardelika5567 " +
            "fwamvm " +
            "Ryder46 " +
            "YaKudZa_MaRo " +
            "TimoG03 "

    const val SUERPCRAFT: String = "TheFlamingOMG " +
            "ImD4mn_x " +
            "Biancirs " +
            "34_ " +
            "Juanilo10 " +
            "prijak125 " +
            "duartetops " +
            "YenSword "

    const val GOMMA: String = "4ch3los " +
            "bemoty " +
            "Clexxer " +
            "GommeHD " +
            "IchMagKeksexD " +
            "Klaus " +
            "lukas81298 " +
            "Marius051099 " +
            "Acex " +
            "FancyPlay " +
            "fantaflash " +
            "Jpx3 " +
            "Kaooot " +
            "LinuxServer " +
            "lvkaas " +
            "Summerfeeling " +
            "sxrhat " +
            "TrainmasterHD " +
            "uScoutz " +
            "einJqn " +
            "ImTxm " +
            "Leoooon " +
            "Zockernetzwerk " +
            "0Taube " +
            "4zig " +
            "Abgxlehnt " +
            "Ason68 " +
            "BeatZap " +
            "BitConi " +
            "DanNick " +
            "debandiete " +
            "DerAutist " +
            "domme0hd " +
            "Dreeaming " +
            "DrNutella " +
            "freudelos " +
            "FourGoldChains " +
            "Fxntom " +
            "iowaniklas " +
            "ItzMarvin23 " +
            "jsnmoin " +
            "KissenschlachtLP " +
            "Laubfrosch7 " +
            "laufe " +
            "Laurens2408 " +
            "lukidercooli " +
            "m0riLp " +
            "Maariuus " +
            "Mxik " +
            "madman1000 " +
            "maisuee " +
            "pewtu " +
            "Polarsterne " +
            "sinischneeflocke " +
            "Slarox " +
            "Tim_Stefan_Maria " +
            "TREM_27 " +
            "Triomino " +
            "UselessGeld " +
            "Vacted " +
            "valentinsan " +
            "Vokabelheft " +
            "Vortrag " +
            "yanno3000 " +
            "zTohru " +
            "zVetrox " +
            "Zunano " +
            "CheeseZocker " +
            "FriendlyDarleen " +
            "nevermiind " +
            "ogii " +
            "Pascas " +
            "Teerve " +
            "114 " +
            "Angestellt " +
            "blutrot " +
            "CalamityFreddi " +
            "CuzImTom " +
            "Cxyy " +
            "DerEisbaer " +
            "DerSchlenderman " +
            "DoctorWann " +
            "Dqniiel " +
            "einChad " +
            "Fernverkehr " +
            "Fey " +
            "FuchsiDE " +
            "gaBer_HD " +
            "geladen " +
            "ItsLazorTV " +
            "kapitulieren " +
            "KleckFleck " +
            "Kruemmel " +
            "la_coneja " +
            "Laugenbrezel " +
            "LeFlurex " +
            "leKireax " +
            "Lenneeey " +
            "Leondopulus " +
            "liebesschwur " +
            "Liisa " +
            "LikeByCookie " +
            "Maloneneis " +
            "MarcelBTW " +
            "Mittelamerika " +
            "Mxln " +
            "Robekh " +
            "Schnitzelmaxl " +
            "Seelenmeer " +
            "Semolius " +
            "SilbernesGold " +
            "SkyDiscovery " +
            "Stepheee " +
            "summervibing " +
            "svaay " +
            "ThatsLuca " +
            "Tschlaubii " +
            "Verlassener " +
            "Voltarix " +
            "W1fu " +
            "xKashiro " +
            "zAimed " +
            "ZettelRaus " +
            "Zwunja " +
            "_starhuntress_ "

    const val GAMSTER: String = "Henriks9 " +
            "Liviu1010 " +
            "ItsB2_ " +
            "Skarnyk " +
            "crosby108 " +
            "M3ti_ " +
            "Mezedak1 " +
            "OsmiumRedox " +
            "pepinillo_crudo " +
            "Space_turtle9 " +
            "Tini_Alina " +
            "_ShadowXD " +
            "mihaaiiii " +
            "Zipette " +
            "Megasus " +
            "Daniell214 " +
            "pintux " +
            "Biee_MB " +
            "ItsKRONX11 " +
            "EroinaMea " +
            "Alex_Rosu " +
            "Raul7896 " +
            "Melanholyyy " +
            "HerDreams " +
            "JustMoon2330 " +
            "qmarcu " +
            "Suffocative " +
            "vxcus " +
            "AutoClickerM5 " +
            "officialMex " +
            "lennoxlotl " +
            "iTz_Lucky " +
            "MutFame " +
            "vento " +
            "Mariaxxaa " +
            "miramausii " +
            "Dark4ever " +
            "Nacktbild " +
            "Bazaraki " +
            "DarkAndBlue " +
            "totKing " +
            "byHugZ " +
            "kyssyou "
}